# This is for testing the project
name: Run-tests
run-name: Run gtests for the project

# Run the testing pipeline on every push a pull request of our assignment* branches and master
on:
  push:
    branches:
      - 'assignment*'
      - master
  pull_request:
    branches:
      - 'assignment*'
      - master
  workflow_dispatch:


jobs:
  # Build the project
  build:
    # Run the tests on ubuntu-20.04
    runs-on: ubuntu-latest
    steps:
      # Install all the dependencies
      - name: install dependencies
        run: >
          sudo apt-get update
          && sudo apt-get install -y build-essential
          clang
          cmake  
          libxerces-c-dev 
          doxygen 
          libgtest-dev 
          && sudo apt-get clean
      # Check out the repository
      - uses: actions/checkout@v4

      - name: Build the project
        run: >
          mkdir build
          && cd build
          && cmake -E env CXXFLAGS="-fsanitize=address" cmake ..
          && make -j 5

      - name: Run the tests
        run: >
          cd build
          && make -j 5 tests
          && ./tests/tests

      - name: Create doxygen documentation
        run: >
          cd build
          && make doc_doxygen
